name: sync up
on:
    push:
        branches:
            - main
jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@main
            with:
              fetch-depth: 0

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@main
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: us-east-2
          - name: CodeGuru Reviewer
            uses: aws-actions/codeguru-reviewer@v1.1
            with:
              s3_bucket: codeguru-reviewer-demo-python-repo-bucket
          - name: Upload review result
            uses: github/codeql-action/upload-sarif@v3
            with:
              sarif_file: codeguru-results.sarif.json

        
          
